services:
  - type: web
    name: e-commerce-backend
    env: python
    repo: https://github.com/Sudhir4500/ecommerce-1.git
    branch: version_3
    rootDir: backend/
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: POSTGRES_URL
        value: "postgresql://ecommerce_5l6z_user:iEJpgvc7xJ6awcZbm0YhMJl8pdRdUGoN@dpg-cuqvdvqj1k6c73cnafag-a.oregon-postgres.render.com/ecommerce_5l6z"
