# Generated by Django 5.1.6 on 2025-02-21 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0002_user_is_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_vendor',
        ),
    ]
