# Generated by Django 5.1.6 on 2025-02-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendormanagement', '0002_vendor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='email',
        ),
    ]
