import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import LoginModal from "./components/modals/LoginModal";
import SignupModal from "./components/modals/Signupmodal";
import Vendormodal from "./components/modals/Vendormodal";
import CategoriesList from "./components/category/CategoriesList";
import AuthInitializer from "./components/AuthInitializer";
import Footer from "./components/Footer";
import Addproducts from "./components/modals/Addproducts";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "multivendor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className=" pt-24">
          <CategoriesList />
         
          <AuthInitializer />
        {children}
        <Addproducts />
      <LoginModal />
      <SignupModal />
      <Vendormodal />
      <Footer />
        </div>
      </body>
    </html>
  );
}
